//CRIA USUARIO

####
POST http://localhost:3306/user/create
Content-Type: application/json

{
    "name": "Gibs",
    "email": "chefencis@any.com",
    "password": "6547893"
}

//BUSCA TODOS USUARIOS

####
GET http://localhost:3306/user/getAll
Content-Type: application/json

//CRIA POST

###
POST http://localhost:3306/post/create
Content-Type: application/json

{
    "photo": "image not found",
    "description": "Lanterna Verde",
    "type": "normal",
    "author_id":"123123123"
}

//BUSCA POR ID DO POST

####
GET http://localhost:3306/post/get/1674778163034
Content-Type: application/json

//BUSCA TODOS OS POSTS

####
GET http://localhost:3306/post/getAll
Content-Type: application/json

//CRIA AMIZADE

###
POST http://localhost:3306/friend/create
Content-Type: application/json

{
    "friendId":"1674763316671"
}

//DESFAZ AMIZADE

###
DELETE  http://localhost:3306/friend/delete
Content-Type: application/json

{
    "friendId":"1674763316671"
}

//BUSCAR TODOS OS AMIGOS

####
GET http://localhost:3306/friend/getAll
Content-Type: application/json